### ISSUE TITLE
va_copy without va_end in mjson_vprintf

### ISSUE THREAD

**Issue by upbeat27** [cesanta/mjson#12]
All calls to va_start and va_copy should have a corresponding va_end.
There should be a va_end in the 'M' formatter of `mjson_vprintf`.
Initially I thought it was as simple as adding the missing call, `va_end(tmp)`.

But, I don't use MSC, and don't know about this:
```c
#if !defined(_MSC_VER) || _MSC_VER >= 1700
#else
#define va_copy(x, y) (x) = (y)
#define snprintf _snprintf
#endif
```
Which looks like the va_end should not be there if using MSC, but should be there otherwise.
Thoughts?

**Comment by upbeat27** [comment]
I came back to this and realized the problem is actually different than a lacking `va_end`.
The problem is there shouldn't be a `va_copy` to begin with. The custom printer should use the same va list as the caller, otherwise anything else after the custom printer and its inputs will be in the wrong spot in the va list.
The `#define va_copy(x, y) (x) = (y)` when using MSC makes it so there is no copy. But for compilers that _do_ have a builtin `va_copy` it actually does make a copy, which means args are advanced separately from the original va list which throws everything off.

**Comment by cpq** [comment]
There was some reason to make a copy.
Actually, `mjson_vprintf()` makes a copy then passes a pointer to va_list, so the issue you're describing should not manifest..
But if you come up with the unit test snippet that shows a problem, I'll update the unit test and fix the code.

**Comment by cpq** [comment]
The HEAD version now has `va_end` so closing this - thanks for reporting!
