### ISSUE TITLE
Multiple definitions when including mjson headers in several source files

### ISSUE THREAD

**Issue by mon** [cesanta/mjson#16]
I separately compile all my source files before linking as a final step. This causes mjson functions to be compiled multiple times, causing multiple definition errors during linking.

What are your thoughts on reverting to the previous .c + .h implementation? It's much more versatile, and as this library is now an arduino one, multiple source files shouldn't be a large burden on novice users.

**Comment by cpq** [comment]
Possibly.
For now, in those extra files, use

```c
#define MJSON_API_ONLY
#include "mjson.h"
```

**Comment by mon** [comment]
Shoot, I completely missed that #define - thanks for the fast reply.

I'll configure it to defined and create an `mjson_impl.c` in my project that undefines it before inclusion. Thanks!
