### ISSUE TITLE
Json parsing issue

### ISSUE THREAD

**Issue by pranamibhatt** [cesanta/mjson#22]
Hi,

I have a json file (attached) that I am trying to parse. I am trying to parse components from the first array using a logic like below:
<<<
  i = 0
  snprintf(path, MAX_JSON_SIZE, "$.Info1[%d].Number", i);
        while (mjson_get_string(buffer, strlen(buffer), path, tmp, sizeof(tmp)) != 0)
        {
                info_num = strtol(tmp, NULL, 16);
                printf ("value read: %x ", info_num);
                memset(tmp, 0, 64);
                i++;
                snprintf(path, MAX_JSON_SIZE, "$.Info1[%d].Number", i);
        }
>>>

When I read back, I find that it is returning the 3 elements (index 0-2) of the first array. It is also returning elements from the second array (index 3-4).
Is this a bug in the library or am I not iterating correctly?

I also tried using mjson_find, but that is also returning the whole json back (with both arrays)

        bool isarray = mjson_find(buffer, strlen(buffer), "$.Info1", &Info, &len) == MJSON_TOK_ARRAY;

        printf("isArray temp: %d %d %s\n", isarray, len, Info);

Please advise.

Thanks!

**Comment by cpq** [comment]
Do not use `%s` for printing a substring inside a large string. Use `%.*d`:

```c
    bool isarray = mjson_find(buffer, strlen(buffer), "$.Info1", &Info, &len) == MJSON_TOK_ARRAY;
    printf("isArray temp: %d %.*s\n", isarray, len, Info);  // <-- note %.*s
```

**Comment by pranamibhatt** [comment]
Thanks for the response. I am going to try this method at my end and see if I can iterate through the first array.
I will post back.

**Comment by pranamibhatt** [comment]
Hi, I did try printing with %.s* and it showed me the first array. However I am having trouble iterating the first array. Is the below logic correct?

        if( mjson_find(buffer, strlen(buffer), "$.Info1", &Info, &len))
                log_err(UNKNOWN_ERROR, "read: %.*s\n", len, Info);

                snprintf(path, MAX_JSON_SIZE, "$.Info1[%d].Number", i);
                while (mjson_get_string(buffer, strlen(buffer), path, tmp, sizeof(tmp)) != 0) {
                        printf ( "string token: %s\n", tmp);
                        i++;
                        snprintf(path, MAX_JSON_SIZE, "$.Info1[%d].Number", i);
                }


I seem to be reading elements from both array 1 and 2. Please do let me know if I need to make adjustments to the while loop.

**Comment by cpq** [comment]
Could you show an example of the JSON string you're operating on, please?

**Comment by pranamibhatt** [comment]
Here is the json I am using:

{
"ServiceName": "XX",
"Version": "1.0.1",
"SchemaVersion": "1.0.0",
"DefaultState": "Enable",
"TimeStamp": "2019-06-23T12:00:00",
"Info1": [
		  {
			"Number": "0x02",
			"Type": "A"
		  },
		  {
			"Number": "0x24",
			"Type": "C"
		  },
		  {
			"Number": "0x11",
			"Type": "B"
		  }
],
"Info2": [
	{
		"RecordID":"0x0001",
		"Number": "0x02",
	},
	{
		"RecordID": "0x0002",
		"Number": "0x24",
	},
	{
		"RecordID": "0x0003",
		"Number": "0x11",
	},
	{
		"RecordID": "0x0004",
		"Number": "0x03",
	},
	{
		"RecordID": "0x0005",
		"Number": "0x05",
	}
	]
	}

**Comment by cpq** [comment]
This iteration should work:

```c
for (int i = 0; ; i++) {
  char path[100], buf[100];
  snprintf(path, sizeof(path), "$.Info1[%d].Number", i);
  if (mjson_get_string(buffer, strlen(buffer), path, buf, sizeof(buf)) <= 0) break;
  printf("%dth element: %s\n", i, buf);

}
```

**Comment by pranamibhatt** [comment]
thanks for the suggestion. I did try the for loop as well.
It seems to print the (3) elements from the first array and then continues to print elements from the second array, starting at index 3.

**Comment by cpq** [comment]
Added these unit tests:

```c
static void test_find(void) {
  const char *p, *str;
  int n;
  // Test array iteration
  str = "{\"a\":[1,2],\"b\":[3,4,5,6]}";
  ASSERT(mjson_find(str, strlen(str), "$.a[0]", &p, &n) == MJSON_TOK_NUMBER);
  ASSERT(mjson_find(str, strlen(str), "$.a[1]", &p, &n) == MJSON_TOK_NUMBER);
  ASSERT(mjson_find(str, strlen(str), "$.a[2]", &p, &n) == MJSON_TOK_INVALID);

  str = "{\"a1\":[{\"x\":1},{\"x\":2}],\"a2\":[{\"x\":3},{\"x\":4}]}";
  ASSERT(mjson_find(str, strlen(str), "$.a1[0].x", &p, &n) == MJSON_TOK_NUMBER);
  ASSERT(mjson_find(str, strlen(str), "$.a1[1].x", &p, &n) == MJSON_TOK_NUMBER);
  ASSERT(mjson_find(str, strlen(str), "$.a1[2].x", &p, &n) ==
         MJSON_TOK_INVALID);
}
```

However these tests do not reproduce your issue. Everything works as expected.
Could you suggest the test that triggers an issue, as a PR/diff to the existing unit test, please?

**Comment by pranamibhatt** [comment]
Hello,
I did some debugging this weekend. I realized two things:
- The issue I reported was due to an outdated version of mjson utility that I was using (2018 version). Upon pulling the latest sources I dont see the original issue I reported on this thread.
- I am now seeing a different iteration issue with the modified json file.
The json file now contains arrays having elements with different fields like below

"Info1": [
		  {
			"Number": "0x02",
			"Type": "A"
		  },
		  {
			"Number": "0x24",
			"Type": "C",
			"Description": "ABC",
		}

The full json file has been attached with the unit test.

I have modified the unit test to add a 'test_json' function. Please take a look at the attached code. I am seeing that the element count is not being reported properly. Please do let me know your thoughts about this use
[test.zip](https://github.com/cesanta/mjson/files/5581056/test.zip)
 case.

Thanks a lot for the help!

**Comment by cpq** [comment]
The reason is that your .json file is malformed. The 5th Info1 element is:

```javascript
		  {
			"Number": "0x26",
			"Type": "B"
			"Description": "ABCD",
			"URI": "abbbccc"
		  },
```

There should be a comma after "B".

**Comment by pranamibhatt** [comment]
Hello,
Thanks for the rectification and the help! I am closing this issue.
