### ISSUE TITLE
64-bit integer support

### ISSUE THREAD

**Issue by boraozgen** [cesanta/mjson#23]
Hi all,

First of all thanks for publishing this great library.

I noticed that `mjson_printf` does not support 64 bit integers (`llu` and `lld` identifiers). Is there a particular reason for this (for example C89 compatibility)? The addition seems pretty simple and I could open a PR for it.

**Comment by cpq** [comment]
The main reason are non-compliant win32 targets. They need something like:

```c
#ifdef _WIN32
#define INT64_FMT "I64d"
#if defined(_MSC_VER) && _MSC_VER < 1700
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif
#endif
#endif
```

If you'd like to file a PR, feel free.
If you do, please add a couple of tests to the unit test, and make sure vc98 and vc2017 targets pass.

**Comment by boraozgen** [comment]
I have the code and tests running using GCC. (`gcc.exe (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0`. )

I don't have a VC environment to test on the mentioned targets. Can you describe how to set up such an environment?

**Comment by cpq** [comment]
Type `make vc98` or `make vc2017`. You have to have Docker running.

**Comment by boraozgen** [comment]
Getting this from Docker:
```
mjson.c
fatal error C1083: Cannot open source file: '../src/mjson.c': No such file or directory
unit_test.c
fatal error C1083: Cannot open source file: 'unit_test.c': No such file or directory
Generating Code...
```
Besides `vc2017` target does not exist in Makefile. I'll dig into this when I have more time.

**Comment by cpq** [comment]
You're right, there was no vc2017 target. I've added just now.

Never ran docker under windows, it definitely looks like a mounting issue - or maybe a Makefile does not set paths?
Could you show the full terminal log please?

**Comment by boraozgen** [comment]
This is the first issue I get when I try to run:

```
PS C:\Users\oezgen.NANTIS\Desktop\mjson\test> mingw32-make vc98
process_begin: CreateProcess(NULL, uname -s, ...) failed.
mingw32-make: Makefile:6: pipe: No error
docker run -v C:/Users/oezgen.NANTIS/Desktop/mjson:C:/Users/oezgen.NANTIS/Desktop/mjson -w C:/Users/oezgen.NANTIS/Desktop/mjson/test docker.io/mgos/vc98 wine cl ../src/mjson.c unit_test.c /nologo /W3 /O1 /I../src /MD -DMJSON_ENABLE_MERGE=1 -DMJSON_ENABLE_PRETTY=1  /Fevc98.exe
docker: Error response from daemon: the working directory 'C:/Users/oezgen.NANTIS/Desktop/mjson/test' is invalid, it needs to be an absolute path.
See 'docker run --help'.
mingw32-make: *** [Makefile:22: vc98] Error 125
```

Apparently this is an issue with paths regarding Docker for Windows: https://github.com/docker/cli/issues/2204

I tried running the `docker run` command directly with a modified path but it then gives the mentioned error: 

```
PS C:\Users\oezgen.NANTIS\Desktop\mjson\test> docker run -v //C/Users/oezgen.NANTIS/Desktop/EKEY/ekey-steuereinheit-sw/mjson:/var/mjson -w /var/mjson/test/ docker.io/mgos/vc98 wine cl ../src/mjson.c unit_test.c /nologo /W3 /O1 /I../src -DMJSON_ENABLE_MERGE=1 -DMJSON_ENABLE_PRETTY=1  /Fevc98.exe
mjson.c
fatal error C1083: Cannot open source file: '../src/mjson.c': No such file or directory
unit_test.c
fatal error C1083: Cannot open source file: 'unit_test.c': No such file or directory
Generating Code...
```

I know this is all Windows crap, so maybe its not worth looking into it.

**Comment by boraozgen** [comment]
I do not require this anymore. Closing.
