### ISSUE TITLE
Floating point precision

### ISSUE THREAD

**Issue by DmiKarasev** [cesanta/mjson#25]
@boraozgen previously opened this issue but closed it because he no longer needed this functionality. However, the issue still needs to be fixed.

Using the `mjson_printf()` function with `"%f"`, the variable with the maximum number of digits after the point is output, for example, in my example

```
{
  "telemetry":{
    "phaseA":{
      "Urms":"220.123000",
      "Irms":"0.100000",
      "p":"0.000000", ...
    }
  ...
  }
}
```

The standard way of limiting `"%.(num)f"` is not implemented. With large telemetry, like mine, the message becomes very long.

Now the only way to display floating numbers adequately is to use `"%g"`:

```
{
  "telemetry":{
    "phaseA":{
      "Urms":"220.123",
      "Irms":"0.1",
      "p":"0", ...
    }
  ...
  }
}
```

but this way is more expensive in terms of performance than `"%f"`

I will ask the question again: Is it planned to support emitting floats with variable precision?

**Comment by cpq** [comment]
@DmiKarasev the width and precision are going to be supported, as floating-point printing will be refactored to avoid stdlib's printf. It does not work as expected in several embedded environments, thus must be implemented independently.

You mention that `%g` is more expensive than `%f`. In all stdlib implementations I know, FP printing is done by a helper function that `snprintf()` calls, and both `%f` and `%g` hit the same codepath - just the params are diffent, like default width of 6. Could you elaborate more on your statement about more expensive %g` processing please?

**Comment by cpq** [comment]
Added `%.*g` support:

```c
char *s = NULL;
mjson_printf(mjson_print_dynamic_buf, &s, "{%Q:%.*g}", "temperature", 3, 1.23456789);
```

Note: `%f` support is gone.
