### ISSUE TITLE
RFE: mjson_get_int_number

### ISSUE THREAD

**Issue by git001** [cesanta/mjson#30]
The `mjson_get_number` returns a double as shown in the examples.

```c
const char *s = "{\"a\":1,\"b\":[2,false]}";  // {"a":1,"b":[2,false]}

// Extract value of `a` into a variable `val` and print its value
double val;
if (mjson_get_number(s, strlen(s), "$.a", &val)) printf("a: %g\n", val);
```

But from my point of view should it be a int.

How about to keep the `mjson_get_number` for double values and add a function which returns the int value?

**Comment by cpq** [comment]
"But from my point of view should it be a int."

What is the justification for that point of view? JSON numbers, like JS numbers, are `double`s.  How the JSON strings like `{"a": 1.234}` should be parsed if a value is an `int`?

If you need an `int`, you could add a simple wrapper:

```c
int mjson_get_number(const char *buf, int len, const char *path, int defvalue) {
  double dv;
  return mjson_get_number(buf, len, path, &dv) ? dv : defvalue;
}
```
