### ISSUE TITLE
Just wondering how to use the escape sequences.

### ISSUE THREAD

**Issue by MikuChan03** [cesanta/mjson#31]
```c
#include "mjson.h"
#include <stdio.h>

int main(){

  const char *s = "{\"a\\u0061\": true}";
  int v;
  if (mjson_get_bool(s, strlen(s), "$.aa", &v))
    printf("boolean: %d\n", v);

  return 0;
}
```

Here I create an object with the key "aa", one "a" is directly written down, the other represented by an escape sequence.
Then I try to get the boolean value from that key, however it doesn't work. What's up with that?

**Comment by cpq** [comment]
That's something too complex for mjson - please use some other tool, that supports escapes in key names.
