### ISSUE TITLE
json printf give wrong result for -10.f

### ISSUE THREAD

**Issue by npk48** [cesanta/mjson#33]
json print -10.f gives -0.x error encoding.
I fixed this by
replace this line
https://github.com/cesanta/mjson/blob/HEAD/src/mjson.c#L604
```c
while (t >= 1.0 && n + s < (int) sizeof(buf)) buf[n++] = '0', t /= 10.0;
```
with 
```c
while (t >= 1.0 && n + s < (int)sizeof(buf)) buf[s+n++] = '0', t /= 10.0;
```

**Comment by cpq** [comment]
@npk48 
Thanks for the fix suggestion - but it is hard to figure out what exactly it fixes.
Could you please provide an exact example, what mjson_printf call do you perform?

**Comment by cpq** [comment]
No response, closing this.
