### ISSUE TITLE
Request for project (C)MakeFile

### ISSUE THREAD

**Issue by Tingles** [cesanta/mjson#36]
Hello,
I've been eyeing this project which looks very helpful for embedded C Json processing.  I wonder if the project will consider adopting a top-level CmakeLists.txt file with instructions on how to configure/build the project.  

I notice a Makefile exists within the test sub-directory, and found it interesting no similar such thing existed at the top-level for easy workflow.  

For me adopting a CMakeLists.txt file would be helpful as I am evaluating using mjson as a library in a larger CMake based project.   I think Cmake is a good option here in this case as it allows cross platform builds.  In the context of mjson I notice there are alternative compile paths based on MSVC or non MSVC compiles.  It seems like a fit use case for a cross platform build tool here.

I could open a pull request with a very basic CmakeLists.txt to expose the projects configure options and provide a basic build target.  Thoughts?

Thanks!

**Comment by Tingles** [comment]
This could be labeled as an enhancement.

**Comment by cpq** [comment]
@Tingles thank you.

CMake is a bloatware so it won't be used by any of Cesanta projects, mjson included.
As for the top-level Makefile, what exactly do you expect to see in it?

**Comment by cpq** [comment]
No response, closing this.
