### ISSUE TITLE
README examples won't compile

### ISSUE THREAD

**Issue by edubart** [cesanta/mjson#40]
I was trying mjson by reading the README, and I've noticed that the examples on the README won't compile. The parsing example uses a `sub` variable that is not declared, the emitting example uses `mjson_snprintf` instead of `mjson_aprintf`  in the dynamic allocated string example.

The RPC example is also calling `jsonrpc_export` with wrong number of arguments.

**Comment by cpq** [comment]
@edubart , thanks for your patience and your report.
