### ISSUE TITLE
[Question] How to parse and get array from JSON string?

### ISSUE THREAD

**Issue by haxpor** [cesanta/mjson#8]
First of all, thank you for great work. I used it and works fine so far.

By the way, I can't seem to fine the way to get an entire array back instead of always know the exact location/index to get value back. Is there a way to do this?

**Comment by vaizmanai** [comment]
you should go over whole array using increment while mjson_get_string() is returning valid value

**Comment by haxpor** [comment]
@vaizmanai thanks. Anyway how can I know the size of such array?

**Comment by vaizmanai** [comment]
@haxpor I am using like this:
```
	int i = 0;
	char *json_port = 0;
	int length_port_string = 0;
	char port_string[MAX_LENGTH_STRING] = {0};

	while(snprintf(string_find_port, MAX_LENGTH_STRING, "$[%d]", i),
	   mjson_find(json_string, json_length, port_string, &json_port, &length_port_string))
	{
		//doing something
		i++;
	}
	
	//here i == size of array
```

**Comment by haxpor** [comment]
That's clever! Thank you for your code example.
I close this issue now.
